language: python
  python:
    - "2.7"
    - "3.5"
  install:
    - pip install codecov
  script:
    - python -m unittest PolynomialTest
    - coverage run PolynomialTest.py
  after_success:
    - codecov
