  language: python
  python:
    - "2.7"
    - "3.5"
  install:
    - pip install codecov
  script:
    - python -m unittest polynomial_test
    - coverage run polynomial_test.py
  after_success:
    - codecov
